export const mockAppointments = [
  {
    id: 1,
    doctor: "Dr. Jean Paul Habimana",
    email: "habimana@chck.rw",
    specialty: "Cardiology",
    date: "12 Oct 2024",
    appointmentDate: "2024-10-12T09:00:00",
    slot: 2,
    status: "confirmed",
  },
  {
    id: 2,
    doctor: "Dr. Marie Claire Uwera",
    email: "uwera@chck.rw",
    specialty: "Dermatology",
    date: "18 Oct 2024",
    appointmentDate: "2024-10-18T14:00:00",
    slot: 5,
    status: "pending",
  },
  {
    id: 3,
    doctor: "Dr. Patrick Nsengimana",
    email: "nsengimana@chck.rw",
    specialty: "General Practice",
    date: "21 Oct 2024",
    appointmentDate: "2024-10-21T10:00:00",
    slot: 1,
    status: "confirmed",
  },
];

export const mockDoctorAppointments = [
  { id: 1, patient: "Jean Paul Niyonzima", patientId: "RW-2034", description: "Follow up chat", slot: 1, status: "approved" },
  { id: 2, patient: "Marie Uwimana", patientId: "RW-2035", description: "First Consultation", slot: 2, status: "pending" },
  { id: 3, patient: "Emmanuel Mukiza", patientId: "RW-2036", description: "Annual checkup", slot: 3, status: "approved" },
  { id: 4, patient: "Claudine Mutoni", patientId: "RW-2037", description: "Follow up", slot: 4, status: "pending" },
];

export const mockTrafficData = [
  { day: "Mon", patients: 18 },
  { day: "Tue", patients: 22 },
  { day: "Wed", patients: 25 },
  { day: "Thu", patients: 20 },
  { day: "Fri", patients: 28 },
  { day: "Sat", patients: 12 },
  { day: "Sun", patients: 8 },
];

export const mockPatients = [
  {
    id: "RW-2034",
    name: "Jean Paul Niyonzima",
    lastAppointment: "12 Oct 2024",
    lastDiagnosis: "Chronic Hypertension and slight heart rhythm irregularity.",
    phone: "+250 788 123 456",
    email: "niyonzima.jp@gmail.com",
  },
  {
    id: "RW-2035",
    name: "Marie Uwimana",
    lastAppointment: "10 Oct 2024",
    lastDiagnosis: "Seasonal allergies - prescribed antihistamines.",
    phone: "+250 792 234 567",
    email: "marie.uwimana@gmail.com",
  },
  {
    id: "RW-2036",
    name: "Emmanuel Mukiza",
    lastAppointment: "8 Oct 2024",
    lastDiagnosis: "Lower back pain - physical therapy recommended.",
    phone: "+250 788 345 678",
    email: "mukiza.emmanuel@gmail.com",
  },
  {
    id: "RW-2037",
    name: "Claudine Mutoni",
    lastAppointment: "5 Oct 2024",
    lastDiagnosis: "Routine checkup - vitals within normal range.",
    phone: "+250 792 456 789",
    email: "claudine.mutoni@gmail.com",
  },
];

export const mockConsultations = [
  {
    id: 1,
    doctor: "Dr. Jean Paul Habimana",
    specialty: "Cardiology Specialist",
    date: "24 Oct 2024",
    time: "10:30",
    diagnosis: "Diagnosis: Hypertension, Moderate - Recommended lifestyle changes and medication.",
    reportAvailable: true,
    hasReport: true,
    status: "completed",
    avatar: "JH",
  },
  {
    id: 2,
    doctor: "Dr. Patrick Nsengimana",
    specialty: "General Practitioner",
    date: "15 Oct 2024",
    time: "14:00",
    diagnosis: "Diagnosis: Seasonal allergies - Prescribed antihistamines.",
    reportAvailable: true,
    hasReport: true,
    status: "completed",
    avatar: "PN",
  },
  {
    id: 3,
    doctor: "Dr. Marie Claire Uwera",
    specialty: "Dermatology",
    date: "8 Oct 2024",
    time: "09:00",
    diagnosis: "Diagnosis: Minor skin irritation - Topical treatment advised.",
    reportAvailable: false,
    hasReport: false,
    status: "completed",
    avatar: "MU",
  },
];

export const mockPrescriptions = [
  {
    id: 1,
    medication: "Amoxicillin",
    expires: "10 Jan 2025",
    dosage: "500 mg",
    frequency: "Twice daily, with food",
    doctor: "Dr. Anne Mutoni",
    doctorAvatar: "AM",
    status: "ready",
    refillsPercent: 100,
  },
  {
    id: 2,
    medication: "Lisinopril",
    expires: "15 Jan 2025",
    dosage: "10 mg",
    frequency: "Once daily, morning",
    doctor: "Dr. Jean Paul Habimana",
    doctorAvatar: "JH",
    status: "processing",
    refillsPercent: 60,
  },
  {
    id: 3,
    medication: "Metformin",
    expires: "Q1 2025",
    dosage: "850 mg",
    frequency: "Twice daily",
    doctor: "Dr. Anne Mutoni",
    doctorAvatar: "AM",
    status: "unavailable",
    refillsPercent: 0,
  },
];

export const mockDoctors = [
  {
    id: 1,
    name: "Dr. Jean Paul Habimana",
    specialty: "Cardiology Specialist",
    rating: 4.8,
    reviews: 120,
    description: "Expert in cardiovascular health with over 12 years of experience.",
    nextSession: "Today, 10:00",
    avatar: "JH",
  },
  {
    id: 2,
    name: "Dr. Patrick Nsengimana",
    specialty: "Cardiologist",
    rating: 4.9,
    reviews: 1024,
    experience: "14 years",
    description: "Specialized in heart conditions and preventive care.",
    avatar: "PN",
  },
  {
    id: 3,
    name: "Dr. Marie Claire Uwera",
    specialty: "General Practitioner",
    rating: 4.7,
    reviews: 89,
    description: "Comprehensive primary care and general health consultations.",
    nextSession: "Tomorrow, 14:00",
    avatar: "MU",
  },
  {
    id: 4,
    name: "Dr. Anne Mutoni",
    specialty: "Pediatrician",
    rating: 4.9,
    reviews: 156,
    description: "Pediatric care specialist focusing on children's health.",
    nextSession: "Today, 15:30",
    avatar: "AM",
  },
  {
    id: 5,
    name: "Dr. Eric Niyomugabo",
    specialty: "General Surgery",
    rating: 4.8,
    reviews: 78,
    description: "General and laparoscopic surgery with 10+ years experience.",
    nextSession: "Tomorrow, 09:00",
    avatar: "EN",
  },
  {
    id: 6,
    name: "Dr. Josiane Mukamana",
    specialty: "Orthopedic Surgery",
    rating: 4.9,
    reviews: 92,
    description: "Orthopedic specialist for joint and bone conditions.",
    nextSession: "Today, 11:00",
    avatar: "JM",
  },
];

// Slot numbers (1, 2, 3...) - max patients per day from doctor schedule
export const mockSlots = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
